# Generated by Django 4.2.7 on 2025-06-11 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('user_inputs', models.JSONField(default=dict, help_text='User provided inputs')),
                ('generation_parameters', models.JSONField(default=dict, help_text='AI generation parameters')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('credits_used', models.PositiveIntegerField(default=0)),
                ('generation_time', models.DurationField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated_papers/pdf/')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='generated_papers/docx/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('template_structure', models.JSONField(default=dict, help_text='JSON structure defining paper sections and requirements')),
                ('style_guidelines', models.TextField(help_text='Formatting and style guidelines')),
                ('citation_style', models.CharField(default='APA', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaperTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('paper_type', models.CharField(choices=[('research', 'Research Paper'), ('essay', 'Essay'), ('thesis', 'Thesis'), ('dissertation', 'Dissertation'), ('report', 'Report'), ('proposal', 'Proposal'), ('review', 'Literature Review')], max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('description', models.TextField()),
                ('system_prompt', models.TextField(help_text='System prompt for AI generation')),
                ('user_prompt_template', models.TextField(help_text='Template for user prompt with placeholders')),
                ('required_fields', models.JSONField(default=list, help_text='List of required input fields from user')),
                ('optional_fields', models.JSONField(default=list, help_text='List of optional input fields from user')),
                ('example_output', models.TextField(blank=True, help_text='Example generated paper')),
                ('validation_rules', models.JSONField(default=dict, help_text='Validation rules for user inputs')),
                ('estimated_credits', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='papers.paperformat')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaperSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('section_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='papers.generatedpaper')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaperFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5')),
                ('comment', models.TextField(blank=True)),
                ('content_quality', models.PositiveIntegerField(default=5)),
                ('structure_quality', models.PositiveIntegerField(default=5)),
                ('language_quality', models.PositiveIntegerField(default=5)),
                ('is_helpful', models.BooleanField(default=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='papers.generatedpaper')),
            ],
        ),
    ]
