# Generated by Django 4.2.7 on 2025-06-11 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paperfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedpaper',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_papers', to='papers.papertemplate'),
        ),
        migrations.AddField(
            model_name='generatedpaper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='papertemplate',
            unique_together={('name', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='papersection',
            unique_together={('paper', 'section_name')},
        ),
        migrations.AlterUniqueTogether(
            name='paperfeedback',
            unique_together={('paper', 'user')},
        ),
    ]
