# Generated by Django 4.2.7 on 2025-06-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_remove_generatedpaper_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedpaper',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
