# Generated by Django 4.2.7 on 2025-06-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_alter_generatedpaper_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpaper',
            name='recovery_context',
            field=models.JSONField(blank=True, help_text='Context data for recovery if generation fails', null=True),
        ),
    ]
