# Generated by Django 4.2.7 on 2025-06-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_generatedpaper_recovery_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperformat',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
