# Generated by Django 4.2.7 on 2025-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_paperformat_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperformat',
            name='prompt_template_en',
            field=models.TextField(blank=True, help_text='Prompt template for LLM in English. Use {name}, {description}, {sections}, {formatting}, {style_guidelines}, {citation_style}, {text} as variables.', null=True),
        ),
        migrations.AddField(
            model_name='paperformat',
            name='prompt_template_zh',
            field=models.TextField(blank=True, help_text='Prompt template for LLM in Chinese. Use {name}, {description}, {sections}, {formatting}, {style_guidelines}, {citation_style}, {text} as variables.', null=True),
        ),
        migrations.AlterField(
            model_name='paperformat',
            name='language',
            field=models.CharField(default='en', help_text="Language code, e.g. 'en', 'zh'", max_length=10),
        ),
    ]
