# Generated by Django 5.2.6 on 2025-09-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0007_paperformat_prompt_template_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paperformat",
            name="style_guidelines",
        ),
        migrations.AddField(
            model_name="paperformat",
            name="credit_price",
            field=models.PositiveIntegerField(
                default=1, help_text="Credit cost to generate this paper format"
            ),
        ),
    ]
