# Generated by Django 5.2.5 on 2025-09-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0008_remove_paperformat_style_guidelines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperformat",
            name="style_guidelines",
            field=models.TextField(
                blank=True, help_text="Formatting and style guidelines"
            ),
        ),
    ]
