# Generated by Django 5.2.5 on 2025-09-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0009_paperformat_style_guidelines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paperformat",
            name="name",
            field=models.CharField(
                choices=[
                    ("docx", "DOCX"),
                    ("pdf", "PDF"),
                    ("latex", "LaTeX"),
                    ("md", "Markdown"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
