# Generated by Django 5.2.5 on 2025-09-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0010_alter_paperformat_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormatCreditPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("docx", "DOCX"),
                            ("pdf", "PDF"),
                            ("latex", "LaTeX"),
                            ("md", "Markdown"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("credit_price", models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
