# Generated by Django 5.2.5 on 2025-09-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0011_formatcreditprice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="papertemplate",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="papertemplate",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="papertemplate",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.RemoveField(
            model_name="papertemplate",
            name="estimated_credits",
        ),
        migrations.RemoveField(
            model_name="papertemplate",
            name="example_output",
        ),
        migrations.RemoveField(
            model_name="papertemplate",
            name="is_premium",
        ),
        migrations.RemoveField(
            model_name="papertemplate",
            name="optional_fields",
        ),
        migrations.RemoveField(
            model_name="papertemplate",
            name="order",
        ),
        migrations.RemoveField(
            model_name="papertemplate",
            name="required_fields",
        ),
        migrations.RemoveField(
            model_name="papertemplate",
            name="validation_rules",
        ),
    ]
