# Generated by Django 5.2.6 on 2025-09-08 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0012_alter_papertemplate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formatcreditprice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
