# Generated by Django 5.2.5 on 2025-08-31 08:03

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("admin", "Admin"), ("normal", "Normal")],
                default="normal",
                max_length=10,
            ),
        ),
    ]
