# Generated by Django 4.2.7 on 2025-06-11 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Provider Name')),
                ('provider_type', models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], max_length=20, verbose_name='Provider Type')),
                ('base_url', models.URLField(help_text='Base URL for the API endpoint', verbose_name='Base URL')),
                ('api_key', models.CharField(blank=True, help_text='API key if required', max_length=500, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('timeout', models.IntegerField(default=30, verbose_name='Timeout (seconds)')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Max Retries')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'LLM Provider',
                'verbose_name_plural': 'LLM Providers',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('language', models.CharField(choices=[('en', 'English'), ('zh-hans', 'Chinese (Simplified)')], default='en', max_length=10, verbose_name='Language')),
                ('prompt_type', models.CharField(choices=[('system', 'System Prompt'), ('user', 'User Prompt'), ('assistant', 'Assistant Prompt')], default='system', max_length=20, verbose_name='Prompt Type')),
                ('template', models.TextField(help_text='Use {variable_name} for variables', verbose_name='Prompt Template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('variables', models.JSONField(default=dict, help_text='JSON object defining template variables', verbose_name='Variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Prompt Template',
                'verbose_name_plural': 'Prompt Templates',
                'ordering': ['-is_default', 'language', 'name'],
                'unique_together': {('name', 'language', 'prompt_type')},
            },
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model Name')),
                ('display_name', models.CharField(max_length=200, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('context_length', models.IntegerField(default=4096, verbose_name='Context Length')),
                ('max_tokens', models.IntegerField(default=2048, verbose_name='Max Tokens')),
                ('temperature_default', models.FloatField(default=0.7, verbose_name='Default Temperature')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('supports_streaming', models.BooleanField(default=True, verbose_name='Supports Streaming')),
                ('cost_per_1k_tokens', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Cost per 1K tokens')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.llmprovider')),
            ],
            options={
                'verbose_name': 'LLM Model',
                'verbose_name_plural': 'LLM Models',
                'ordering': ['-is_default', 'display_name'],
                'unique_together': {('provider', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LLMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_temperature', models.FloatField(default=0.7, verbose_name='Default Temperature')),
                ('default_max_tokens', models.IntegerField(default=2048, verbose_name='Default Max Tokens')),
                ('enable_streaming', models.BooleanField(default=True, verbose_name='Enable Streaming')),
                ('enable_caching', models.BooleanField(default=True, verbose_name='Enable Caching')),
                ('cache_ttl', models.IntegerField(default=3600, verbose_name='Cache TTL (seconds)')),
                ('rate_limit_per_minute', models.IntegerField(default=60, verbose_name='Rate Limit per Minute')),
                ('enable_logging', models.BooleanField(default=True, verbose_name='Enable Logging')),
                ('log_level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10, verbose_name='Log Level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('default_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_configs', to='core.llmmodel', verbose_name='Default Model')),
                ('default_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_configs', to='core.llmprovider', verbose_name='Default Provider')),
            ],
            options={
                'verbose_name': 'LLM Configuration',
                'verbose_name_plural': 'LLM Configurations',
            },
        ),
    ]
