# Generated by Django 5.2.4 on 2025-07-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_credittransaction_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of package features', null=True),
        ),
    ]
