# Generated by Django 5.2.6 on 2025-09-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_package_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="badge",
            field=models.CharField(
                blank=True,
                help_text="Badge label for package",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="bonus_credits",
            field=models.PositiveIntegerField(
                default=0, help_text="Bonus credits included in package"
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Color for frontend display",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="limitation",
            field=models.CharField(
                blank=True,
                help_text="Limitation or note for package",
                max_length=200,
                null=True,
            ),
        ),
    ]
